set.seed(1)
controlsubslist <- list("GlobalOffensive",
                        "  tacticalgear",
                        "  boardgames",
                        "  adhdwomen",
                        "  Bitcoin",
                        "  woodworking",
                        "  airsoft",
                        "  ftm",
                        "  PokemonTCG",
                        "  TheSimpsons",
                        "  baseballcards",
                        "  OnePunchMan",
                        "  ShitPostCrusaders",
                        "  okbuddychicanery",
                        "  Sneakers",
                        "  mariokart",
                        "  btd6",
                        "  MurderedByWords",
                        "  VALORANT",
                        "  pregnant",
                        "  Watches",
                        "  jobs",
                        "  amcstock",
                        "  loseit",
                        "  singapore",
                        "  REBubble",
                        "  southpark",
                        "  walmart",
                        "  projectzomboid",
                        "  Aquariums",
                        "  PokemonHome",
                        "  cscareerquestions",
                        "  magicTCG",
                        "  XboxSeriesX",
                        "  vegan",
                        "  mbti",
                        "  Piratefolk",
                        "  Gamingcirclejerk",
                        "  chelseafc",
                        "  thebachelor",
                        "  PcBuild",
                        "  Austin",
                        "  AskOuija",
                        "  Chainsawfolk",
                        "  batman",
                        "  namenerds",
                        "  totalwar",
                        "  minnesotavikings",
                        "  servant",
                        "  Catholicism",
                        "  gadgets",
                        "  london",
                        "  NoMansSkyTheGame",
                        "  MechanicAdvice",
                        "  minnesota",
                        "  arknights",
                        "  MarvelStudiosSpoilers",
                        "  reddeadredemption",
                        "  replika",
                        "  Starfield",
                        "  WTF",
                        "  legaladvice",
                        "  Denver",
                        "  whatcarshouldIbuy",
                        "  ClashRoyale",
                        "  lotrmemes",
                        "  ShingekiNoKyojin",
                        "  MonsterHunter",
                        "  kpop",
                        "  InstacartShoppers",
                        "  BocchiTheRock",
                        "  Marriage",
                        "  Finanzen",
                        "  Amd",
                        "  Jokes",
                        "  popheads",
                        "  21stCenturyHumour",
                        "  InstaCelebsGossip",
                        "  amiugly",
                        "  HomeImprovement",
                        "  BoysPlanet",
                        "  LosAngeles",
                        "  doodoofard",
                        "  pkmntcgtrades",
                        "  travel",
                        "  brasilivre",
                        "  Accounting",
                        "  Portland",
                        "  SaimanSays",
                        "  lostarkgame",
                        "  insanepeoplefacebook",
                        "  askTO",
                        "  science",
                        "  DarkTide",
                        "  CasualConversation",
                        "  runescape",
                        "  realhousewives",
                        "  pathofexile",
                        "  perfectlycutscreams",
                        "  playstation",
                        "  raisedbynarcissists",
                        "  MarriedAtFirstSight",
                        "  CitiesSkylines",
                        "  counting",
                        "  survivor",
                        "  whenthe",
                        "  AskFrance",
                        "  gameofthrones",
                        "  pokemontrades",
                        "  CarTalkUK",
                        "  CrappyDesign",
                        "  perth",
                        "  Buttcoin",
                        "  Tools",
                        "  LastEpoch",
                        "  chess",
                        "  AskWomenOver30",
                        "  cyberpunkgame"
)

random15 <- sample(controlsubslist, 15) 
print(random15)

# AskOuija and Replika must be replaced: AskOuija is a forum in which users only give single letter answers (as in an ouija board) and Replika contains NSFW/explicit content that must have been missed by the site generating this list (subredditstats.com)

newsample  <- setdiff(controlsubslist, random15)

set.seed(3)
subs2 <- sample(newsample, 2)
print(subs2)
